### ISSUE TITLE
error  occurs  in the  “Simple FWI Example”  

### ISSUE THREAD

**Issue by ITcooker-liu** [AmirMardan/PyFWI#16]
fortunately, I've already completed the seismic wave forward simulation. But  when I  continued with inversion which is

 “fwi = FWI(d_obs, inpa, src, rec_loc, model_shape,
          components=seisout, chpr=20, n_well_rec=n_well_rec)”

error  occurs  ：

E:\fwi\.venv\Scripts\python.exe E:\fwi\fwi_test.py 
Device 0 is chosen.
Traceback (most recent call last):
  File "E:\fwi\fwi_test.py", line 102, in <module>
    components=seisout, chpr=20, n_well_rec=n_well_rec)
  File "E:\fwi\.venv\lib\site-packages\PyFWI\fwi.py", line 38, in __init__
    super().__init__(inpa, src, rec_loc, model_shape, n_well_rec=n_well_rec, chpr=chpr, components=components)
  File "E:\fwi\.venv\lib\site-packages\PyFWI\wave_propagation.py", line 623, in __init__
    set_env_variable=set_env_variable)
  File "E:\fwi\.venv\lib\site-packages\PyFWI\wave_propagation.py", line 181, in __init__
    self.ctx = cl.create_some_context()
  File "E:\fwi\.venv\lib\site-packages\pyopencl\__init__.py", line 1674, in create_some_context
    "create_some_context. (left over: '%s')" % ":".join(answers))
pyopencl._cl.RuntimeError: not all provided choices were used by create_some_context. (left over: '0')
Device 0 is chosen.

I don't know why this is happening. because I have  change  “set_env_variable=False” in the  forward modeling.

**Comment by AmirMardan** [comment]
Hi,

Could you please uninstall the old version and install the package using 
```
python -m pip install git+https://github.com/AmirMardan/PyFWI.git@dev
```
Then, use the following example to perform FWI.
You will be asked to choose the device on which you want to run the code. 

https://github.com/AmirMardan/PyFWI/blob/16-error-occurs-in-the-simple-fwi-example/example/fwi_example_surface.py

Please let me know if there is any problems.

**Comment by ITcooker-liu** [comment]
Thank you very much！It works.
When I looked at the source code in the function "def  __kernel_gradient"   of   the  wave_propagation.py, I found a possible bug, but I'm not sure.

 def __kernel_gradient(self, res, s, coeff=-1):
        chpc = self.nchp - 1

        coeff = np.int32(coeff)

        vx_show = np.zeros((self.tnz, self.tnx), dtype=np.float32)
        adj_vx_show = np.zeros((self.tnz, self.tnx), dtype=np.float32)

        t_src = np.int32(self.nt_ext)
        # time loop
        for t in range(self.nt - 1, 0, -1):  # range(self.nt-1,self.nt-2,-1):#
            if t == self.chp[chpc]:
                vx = np.copy(self.W['vx'][:, :, s, chpc])
                cl.enqueue_copy(self.queue, self.vx_b, vx)

                vz = np.copy(self.W['vz'][:, :, s, chpc])
                cl.enqueue_copy(self.queue, self.vz_b, vz)

                taux = np.copy(self.W['taux'][:, :, s, chpc])
                cl.enqueue_copy(self.queue, self.taux_b, taux)

                tauz = np.copy(self.W['tauz'][:, :, s, chpc])
                cl.enqueue_copy(self.queue, self.tauz_b, tauz)

                tauxz = np.copy(self.W['tauxz'][:, :, s, chpc])
                cl.enqueue_copy(self.queue, self.tauz_b, tauxz)

                chpc -= 1
where  in  "cl.enqueue_copy(self.queue, self.tauz_b, tauxz)", Whether  "self.tauz_b" should be changed  to    "self.tauxz_b".

**Comment by AmirMardan** [comment]
Thank you, I fixed it in this [commit ](https://github.com/AmirMardan/PyFWI/commit/03ba4f0653cae570fdacc705eaef94be92314e64)

**Comment by ITcooker-liu** [comment]
Hi
Excuse me，which branch should I install  for  a stable version? main or dev?  Thank you for your help.

**Comment by AmirMardan** [comment]
Main, you can also use `python -m pip install PyFWI`
