### ISSUE TITLE
PyFWI on Windows

### ISSUE THREAD

**Issue by 1902912604** [AmirMardan/PyFWI#3]
Hello, can this tool be used on Windows?

**Comment by AmirMardan** [comment]
Hi
Yes, you can install the package using 

```
py -m pip install PyFWI
```

if you get any errors, please send us more details about the error you get.

**Comment by 1902912604** [comment]
Hi
When I used ‘’pip install PyFWI‘’ to download PyFWI, the following error occurred：

ERROR: Could not find a version that satisfies the requirement PyFWI (from versions: none)
ERROR: No matching distribution found for PyFWI

**Comment by AmirMardan** [comment]
Hi 
Thanks for sending the details. Try
``` 
pip3 install PyFWI
```
and let us know if any errors come up. 
This is not related to the current error but you should know this package works with Python 3.10.

**Comment by 1902912604** [comment]
Hi，
Thanks for your reply.    I tried your suggestions , but the following problems occurred:
`ERROR: Failed building wheel for pyopencl`

**Comment by AmirMardan** [comment]
Ok that's because installing pyopencl on Windows is sometimes problematic. Follow the instructions in following link and let us know please if everything is good.

https://forum.image.sc/t/error-while-installing-pyopencl-on-windows-10/44534

**Comment by AmirMardan** [comment]
You can get the required informations and files, from following link

https://pypi.org/project/pyopencl/2021.2.10/#files

However I suggest you clone PyFWI repository instead of installing from PyPI for now.
