### ISSUE TITLE
Tried to run this but ran into problems. I'm on a M1 MacOS laptop. I tried to run it via both standard m1 modes and Rosetta mode to mimic Intel-based mac behavior.

### ISSUE THREAD

**Issue by AmirMardan** [AmirMardan/PyFWI#4]
Tried to run this but ran into problems. I'm on a M1 MacOS laptop. I tried to run it via both standard m1 modes and Rosetta mode to mimic Intel-based mac behavior. 

The error I get (not doing any Rosetta fanciness) is 
```
(pyfwi) JustinGosses_per:PyFWI-test justingosses$ pip install PyFWI
Collecting PyFWI
  Using cached PyFWI-0.1.7-py3-none-any.whl (68 kB)
Collecting datetime
  Downloading DateTime-4.5-py2.py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 1.3 MB/s eta 0:00:00
Collecting scipy
  Using cached scipy-1.8.1-cp310-cp310-macosx_12_0_arm64.whl (28.7 MB)
Collecting segyio
  Using cached segyio-1.9.6.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ry/tr7t3nh122z_0n6rz2cl3lv40000gn/T/pip-install-guz0ovaa/segyio_20210f3369a9411ba04344ec9a238dd0/setup.py", line 3, in <module>
          import skbuild
      ModuleNotFoundError: No module named 'skbuild'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Googled this error and seems to be related to errors others have had with segyio. **Maybe someone with experience with segyio would be able to help?**

_Originally posted by @JustinGOSSES in https://github.com/softwareunderground/awesome-open-geoscience/issues/179#issuecomment-1179925441_

**Comment by JustinGOSSES** [comment]
Thanks for the info. I'll try later this week. Ping me here or on the awesome list if I don't reply respond by next week.

**Comment by AmirMardan** [comment]
@JustinGOSSES Just wondering if it worked for you.

**Comment by JustinGOSSES** [comment]
Sorry for the late response. Installation does work now, so that's great. 

I ran into another issue when going through the example in docs. I'll make second issue for that.

**Comment by AmirMardan** [comment]
Thanks for checking. If you still have a problem with `segyio`, you can't use `import PyFWI.model_dataset as md`. So, you can't use any synthetic models that PyFWI provides. You should create models instead of `Model = md.ModelGenerator('louboutin'); model = Model()`. This model must be a dictionary with at least three keys as P-wave velocity (`vp`), S-wave velocity (`vs`), and density (`rho`).

This gist might help for a simple acoustic case: 
[https://gist.github.com/AmirMardan/04b4c516032aab22683f30c0f8e85de6](https://gist.github.com/AmirMardan/04b4c516032aab22683f30c0f8e85de6)
