### ISSUE TITLE
example

### ISSUE THREAD

**Issue by 1902912604** [AmirMardan/PyFWI#9]
Hi Amir, thanks a lot for the work you do. 

Could you please provide an example of the marmousi2 model? I'm interested in understanding its application in seismic imaging.

**Comment by AmirMardan** [comment]
Hi,

Following [this example](https://github.com/AmirMardan/PyFWI/blob/main/example/fwi_example.ipynb), you should be able to estimate the properties of the Marmousi model.
Some applications of PyFWI for inverting elastic/petrophysical properties of the Marmousi model can be seen in our papers available at [here](https://amirmardan.github.io/tlfwi.html).
